title: Yunyu Tao's Homepage
page-top-title: Berlin
top-section-bg-text: Physics
backgrounds:
  - static/assets/background/background_2.jpeg
background-interval-ms: 7000
background-overlay: 0
copyright-text: '&copy; Yunyu Tao 2025-2026. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/Friedr1ch
license-link:
  text: License
  href: https://github.com/Friedr1ch/Friedr1ch.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: Yunyu Tao&ensp;|&ensp;Berlin
    href: '#page-top' # Default to '#<id>' if not specified
  - id: share
    nav: SHARE
    title: Share
    icon: bi-file-text-fill

